GEOCODING_BATCH_SIZE = ENV['GEOCODING_BATCH_SIZE'].try(:to_i) || 100
Rails.logger.info "Using GEOCODING_BATCH_SIZE=#{GEOCODING_BATCH_SIZE}"

GEOCODING_DSTK_STREET2COORD_URL = ENV['GEOCODING_DSTK_STREET2COORD_URL'] || raise("missing env var: GEOCODING_DSTK_STREET2COORD_URL")
Rails.logger.info "Using GEOCODING_DSTK_STREET2COORD_URL=#{GEOCODING_DSTK_STREET2COORD_URL}"
